#!/usr/bin/env bash

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Export GoPath
export GOPATH=$HOME/go

# Include ~/bin and /usr/local/bin in the PATH
export PATH=~/.rbenv/shims:~/.rbenv/bin:~/bin:$GOPATH/bin:/usr/local/bin:$PATH

# append to the history file, don't overwrite it
shopt -s histappend
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Get rid of ctrl-o binding on os x
stty discard undef

# Alias definitions.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# If we have rbenv installed, lets use it
if which -s rbenv; then eval "$(rbenv init -)"; fi

# Setup a sane editor as the default
if which -s gvim; then
    EDITOR=gvim
elif which -s vim; then
    EDITOR=vim
elif which -s vi; then
    EDITOR=vi
fi
export EDITOR

# Sure we have a color terminal
export CLICOLOR=1

# Aliases
alias sail='cd ~/Code/sailthru'
alias sailthru='cd ~/Code/sailthru'

alias shop='cd ~/Code/shopalytic'
alias shopalytic='cd ~/Code/shopalytic'

alias lot='cd ~/Code/lot18'
alias lot18='cd ~/Code/lot18'

alias pen='cd ~/Code/penrose'

# Setup gitbranch info function
function git_branch {
    git_branch_var=$(git symbolic-ref -q --short HEAD 2>/dev/null)
    if [ $git_branch_var ]; then
        echo "($git_branch_var) "
    fi
}

PS1="[\u@\h \w] \$(git_branch)\$ "

if [ -S "$SSH_AUTH_SOCK" ] && [ ! -h "$SSH_AUTH_SOCK" ]; then
    ln -sf "$SSH_AUTH_SOCK" ~/.ssh/ssh_auth_sock
fi
export SSH_AUTH_SOCK=~/.ssh/ssh_auth_sock
